### ISSUE TITLE
Error while activating orbital rail cannon

### ISSUE THREAD

**Issue by EagleDev91** [ChaoticAlexander/helldivers2-stratagem-activator#7]
Hey,

first, I really appreciate your work!

Here is my issue:
When activating the orbital rail cannon, I get a Windows popup with the error message "Error while writing config file: config.ini".
The naming of parameter is correct.

Can you look into this by time?

Thank you,
EagleDev

**Comment by ChaoticAlexander** [comment]
Hmm.. this must have happened due to an IO error

But just a few questions to make sure and narrow it down.
- does this only happen on the orbital cannon? Do the rest work?
- can you try and see if there is a config.ini file next to the stratagems.exe file?

if there isn't a file, try first running the settings.exe and generate the config file that way

If none of these work, exclude the folder including these files from windows defender.

I'll probably upload signed .exe's one of these days, so the window defender part should get fixed then.

Anyway please let me know of the results so that I know what to look for.

**Comment by EagleDev91** [comment]
Yeah, Strangely enough, only the rail cannon is affected.
There is the config.ini, which was created after I run the settngs.exe

Excluding your folder/scripts doesn't change the behavior.

Do not hesitate to involve me further in the troubleshooting. Can I somehow activate a debug log?

**Comment by ChaoticAlexander** [comment]
I really appreciate your willingness to help!
I'll take a look after work and let you know.

**Comment by EagleDev91** [comment]
I'm so dumb. A friend give me the hint after sharing my Loupedeck Profile, that I doubled the script path as parameter 🤦‍♂️🤣

No wonder it doesn't work.

**Comment by ChaoticAlexander** [comment]
Hahahah stuff like that happens man

Still, I should probably add some error handling for cases like these.
So thanks nonetheless for the insight! 😁
